name: GitHub Actions
run-name: Personal Portfolio Project - running actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: test project
        run: npm run test
